services:
    postgres:
        container_name: postgres_db
        image: postgres
        environment:
            POSTGRES_USER: lolucode
            POSTGRES_PASSWORD: password
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5434:5432"
        networks:
            - postgres
        restart: unless-stopped
    pgadmin:
        container_name: pgadmin_db
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "5050:80"
        networks:
            - postgres
        restart: unless-stopped

    morphine:
        image: lolucodes/morphine:v3
        container_name: morphine
        ports:
            - "8080:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=docker
        networks:
            - spring
            - postgres
        depends_on:
            - maildev
            - postgres


    maildev:
        image: maildev/maildev
        ports:
            - "1070:1080"

networks:
    postgres:
        driver: bridge
    spring:
        driver: bridge

volumes:
    postgres:
    pgadmin: